### ISSUE TITLE
Use Symbolic Icons

### ISSUE THREAD

**Issue by yousafesaeed** [fablevi/OnTheTop-fablevi.github.io#1]
Instead of using both light and dark icons, consider using symbolic icons to adhere to the theme color. Use a black SVG and append `-symbolic` to its name, ex: `Above-symbolic.svg`.

**Comment by fablevi** [comment]
Hey @yousafesaeed :)

So my main problem is, probably in the future gnome will be use light and dark themed top panel. So i made 2 type of svg-s, one with light and one with dark theme. I tryed to use chatGPT to help me, because this is my first time to use gjs and made an extension. So if you watch my code you probably see that i watch the main theme name if got dark in the name. This is how its work on ubuntu (yaru-blue and yaru-dark-blue), but if a distribution like Fedora uses Adwaita i can't tell the difference. I tryed multiple way to do it and watched back other extensions code but i didnt got any solution. 
If you can help me, then i am listening :)

Thanks for the opened issue and sorry for my english

Levi

**Comment by fablevi** [comment]
> Instead of using both light and dark icons, consider using symbolic icons to adhere to the theme color. Use a black SVG and append `-symbolic` to its name, ex: `Above-symbolic.svg`.


Hey @yousafesaeed :)

So my main problem is, probably in the future gnome will be use light and dark themed top panel. So i made 2 type of svg-s, one with light and one with dark theme. I tryed to use chatGPT to help me, because this is my first time to use gjs and made an extension. So if you watch my code you probably see that i watch the main theme name if got dark in the name. This is how its work on ubuntu (yaru-blue and yaru-dark-blue), but if a distribution like Fedora uses Adwaita i can't tell the difference. I tryed multiple way to do it and watched back other extensions code but i didnt got any solution.
If you can help me, then i am listening :)

Thanks for the opened issue and sorry for my english

Levi

**Comment by fablevi** [comment]
> Instead of using both light and dark icons, consider using symbolic icons to adhere to the theme color. Use a black SVG and append `-symbolic` to its name, ex: `Above-symbolic.svg`.

Okey i read it again, and i get what you say. I will try it out:)
